version: "3.9"

services:
  redis:
    image: redis:8.4-alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data    # persistence between container restarts
    restart: unless-stopped

  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    container_name: tictactoe-backend
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=tempo:4317
      - OTEL_SERVICE_NAME=tictactoe-backend
    depends_on:
      - redis
      - tempo
    restart: unless-stopped

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"   # tempo
      - "4317:4317"   # otlp grpc
      - "4318:4318"   # otlp http

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    depends_on:
      - tempo

volumes:
  redis-data:
